spring:
    datasource:
        url: jdbc:postgresql://localhost:5332/customer
        username: evansdev
        password: password
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    application:
        name: spring-boot-java-api
    profiles:
        active: dev

server:
    port: 8000
    error:
        include-message: always
